Repository s-yeong/There-Server, pull requests merged in 2022-08, with the labels that each got.

#41 채팅방 조회 API 수정 및 Portfolio API 기능 구현
  src/main/java/com/there/src/chat/ChatContentDao.java
  src/main/java/com/there/src/chat/ChatContentProvider.java
  src/main/java/com/there/src/chat/ChatContentService.java
  src/main/java/com/there/src/chat/ChatController.java
  src/main/java/com/there/src/chat/ChatRoomDao.java
  src/main/java/com/there/src/portfolio/PortfolioController.java
  src/main/java/com/there/src/portfolio/PortfolioDao.java
  src/main/java/com/there/src/portfolio/PortfolioService.java
  src/main/java/com/there/src/portfolio/config/BaseResponseStatus.java
  src/main/java/com/there/src/portfolio/model/PatchPortfolioReq.java
Labels: enhancement

#42 채팅방 관련 API 오류 수정
  src/main/java/com/there/src/chat/ChatContentDao.java
  src/main/java/com/there/src/chat/ChatController.java
  src/main/java/com/there/src/chat/ChatRoomProvider.java
  src/main/java/com/there/src/portfolio/PortfolioController.java
Labels: bug

#54 REFACTOR: validation Merge
  src/main/java/com/there/src/chat/config/BaseException.java
  src/main/java/com/there/src/chat/config/BaseResponse.java
  src/main/java/com/there/src/chat/config/BaseResponseStatus.java
  src/main/java/com/there/src/like/config/BaseException.java
  src/main/java/com/there/src/like/config/BaseResponse.java
  src/main/java/com/there/src/like/config/BaseResponseStatus.java
  src/main/java/com/there/src/portfolio/PortfolioController.java
  src/main/java/com/there/src/portfolio/config/BaseException.java
  src/main/java/com/there/src/portfolio/config/BaseResponse.java
  src/main/java/com/there/src/portfolio/config/BaseResponseStatus.java
Labels: documentation

#55 REFACTOR: validation Merge
  src/main/java/com/there/src/portfolio/PortfolioProvider.java
  src/main/java/com/there/src/portfolio/PortfolioService.java
Labels: documentation

#58 REFACTOR: validation Merge
  src/main/java/com/there/config/BaseResponseStatus.java
  src/main/java/com/there/src/comment/config/BaseResponse.java
  src/main/java/com/there/src/history/HistoryController.java
  src/main/java/com/there/src/history/HistoryProvider.java
  src/main/java/com/there/src/history/HistoryService.java
  src/main/java/com/there/src/history/cofig/BaseException.java
  src/main/java/com/there/src/history/cofig/BaseResponse.java
  src/main/java/com/there/src/history/cofig/BaseResponseStatus.java
  src/main/java/com/there/src/post/PostController.java
  src/main/java/com/there/src/post/PostProvider.java
  src/main/java/com/there/src/post/PostService.java
  src/main/java/com/there/src/post/config/BaseException.java
  src/main/java/com/there/src/post/config/BaseResponse.java
  src/main/java/com/there/src/post/config/BaseResponseStatus.java
  src/main/java/com/there/src/search/SearchController.java
  src/main/java/com/there/src/search/SearchProvider.java
  src/main/java/com/there/src/search/SearchService.java
  src/main/java/com/there/src/search/config/BaseException.java
  src/main/java/com/there/src/search/config/BaseResponse.java
  src/main/java/com/there/src/search/config/BaseResponseStatus.java
Labels: documentation

#66 REFACTOR: 채팅방 목록 조회 API Result 수정
  src/main/java/com/there/src/chat/ChatContentDao.java
  src/main/java/com/there/src/chat/ChatContentProvider.java
  src/main/java/com/there/src/chat/ChatController.java
  src/main/java/com/there/src/chat/ChatRoomDao.java
  src/main/java/com/there/src/chat/ChatRoomProvider.java
  src/main/java/com/there/src/chat/model/GetChatContentRes.java
  src/main/java/com/there/src/chat/model/GetRoomInfoRes.java
  src/main/java/com/there/src/chat/model/GetRoomListRes.java
  src/main/java/com/there/src/chat/model/GetUnreadCountRes.java
  src/main/java/com/there/src/point/PointController.java
Labels: bug

#67 REFACTOR: 메시지 조회 API 반환 객체 변경
  src/main/java/com/there/src/chat/ChatController.java
Labels: Edit
